In [30]:
import numpy as np

# NumPy-based Matrix Calculator

In [36]:
def get_matrix():
    """Function to take user input for a matrix."""
    rows = int(input("Enter number of rows: "))
    cols = int(input("Enter number of columns: "))
    print("Enter matrix row by row, separating numbers with spaces:")
    matrix = []
    for _ in range(rows):
        matrix.append(list(map(float, input().split())))
    return np.array(matrix)

def matrix_operations():
    """Function to perform matrix operations"""
    print("\nMatrix Calculator - Choose an Operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Scalar Multiplication")
    print("5. Transpose")
    print("6. Determinant")
    print("7. Inverse")
    print("8. Eigenvalues & Eigenvectors")
    print("9. Exit")
    
    choice = input("Enter choice (1-9): ")
    
    if choice in ('1', '2', '3'):
        print("\nEnter first matrix:")
        A = get_matrix()
        print("\nEnter second matrix:")
        B = get_matrix()
        if choice == '1':
            print("\nResult of Addition:")
            print(A + B)
        elif choice == '2':
            print("\nResult of Subtraction:")
            print(A - B)
        elif choice == '3':
            print("\nResult of Multiplication:")
            print(np.dot(A, B))
    
    elif choice == '4':
        print("\nEnter matrix:")
        A = get_matrix()
        scalar = float(input("Enter scalar value: "))
        print("\nResult of Scalar Multiplication:")
        print(A * scalar)
    
    elif choice == '5':
        print("\nEnter matrix:")
        A = get_matrix()
        print("\nTranspose of the Matrix:")
        print(A.T)
    
    elif choice == '6':
        print("\nEnter square matrix:")
        A = get_matrix()
        if A.shape[0] != A.shape[1]:
            print("Error: Determinant can only be computed for square matrices.")
        else:
            print("\nDeterminant:", np.linalg.det(A))
    
    elif choice == '7':
        print("\nEnter square matrix:")
        A = get_matrix()
        if A.shape[0] != A.shape[1]:
            print("Error: Inverse can only be computed for square matrices.")
        else:
            try:
                print("\nInverse:")
                print(np.linalg.inv(A))
            except np.linalg.LinAlgError:
                print("Error: Matrix is singular and cannot be inverted.")
    
    elif choice == '8':
        print("\nEnter square matrix:")
        A = get_matrix()
        if A.shape[0] != A.shape[1]:
            print("Error: Eigenvalues can only be computed for square matrices.")
        else:
            eigenvalues, eigenvectors = np.linalg.eig(A)
            print("\nEigenvalues:", eigenvalues)
            print("\nEigenvectors:")
            print(eigenvectors)
    
    elif choice == '9':
        print("Exiting program.")
        return
    
    else:
        print("Invalid choice. Please select a valid option.")
    
    # Run again
    matrix_operations()

if __name__ == "__main__":
    matrix_operations()


Matrix Calculator - Choose an Operation:
1. Addition
2. Subtraction
3. Multiplication
4. Scalar Multiplication
5. Transpose
6. Determinant
7. Inverse
8. Eigenvalues & Eigenvectors
9. Exit


Enter choice (1-9):  9


Exiting program.


# Practice NumPy 

In [50]:
a = np.array([1,7,3])
print(a)

[1 7 3]


In [66]:
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.6, 3.4]], dtype='float64')
print(b)

[[1.  2.  3. ]
 [4.  5.6 3.4]]


In [44]:
b.ndim

2

In [46]:
b.shape

(2, 3)

In [54]:
a.ndim

1

In [56]:
a.dtype

dtype('int64')

In [60]:
b.dtype

dtype('float64')

In [68]:
b.itemsize

8

In [70]:
b.size

6

In [72]:
a.nbytes

24

In [76]:
c = np.array([[1,2,3,4],[3,4,5,6]])
print(c)

[[1 2 3 4]
 [3 4 5 6]]


In [78]:
c[1,3]

6

In [84]:
c[-2,-2]

3

In [86]:
c[0,:]

array([1, 2, 3, 4])

In [88]:
c[:,2]

array([3, 5])

In [94]:
c[0,1:2:1]

array([2])

In [96]:
c[1,2]=77

In [98]:
print(c)

[[ 1  2  3  4]
 [ 3  4 77  6]]


In [100]:
d = np.array([[[1,2,3,4],[3,4,5,6]],[[11,21,13,41],[31,41,51,16]]])
print(d)

[[[ 1  2  3  4]
  [ 3  4  5  6]]

 [[11 21 13 41]
  [31 41 51 16]]]


In [102]:
d[0,1,3]

6

In [108]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [110]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [114]:
np.full((2,2),9,dtype='float32')

array([[9., 9.],
       [9., 9.]], dtype=float32)

In [124]:
np.full_like(d.shape,3)

array([3, 3, 3])

In [134]:
np.random.rand(4,2,3)

array([[[0.95558205, 0.4093797 , 0.14290581],
        [0.89196927, 0.15221799, 0.47016453]],

       [[0.43689601, 0.49466928, 0.30913496],
        [0.00460831, 0.94378029, 0.43473117]],

       [[0.9917087 , 0.21437454, 0.66320465],
        [0.81113363, 0.484303  , 0.06960102]],

       [[0.23893628, 0.26504012, 0.43378476],
        [0.93242299, 0.82833657, 0.6619218 ]]])

In [136]:
np.random.sample(4)

array([0.48479195, 0.78263212, 0.65382485, 0.3398618 ])

In [142]:
np.random.randint(-100,100,size=(3,3))

array([[ 41,  81,   2],
       [ 51, -57,   6],
       [  5,  -8, -24]])

In [144]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [164]:
arr = np.array([[1,2,4]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 4]
 [1 2 4]
 [1 2 4]]


In [168]:
out = np.ones((4,4))
print(out)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [176]:
z = np.zeros((3,3))
z[1,1]=56
print(z)
out[0:-1,0:-1]=z

[[ 0.  0.  0.]
 [ 0. 56.  0.]
 [ 0.  0.  0.]]


In [188]:
aa = np.array([1,2,3])
aa

array([1, 2, 3])

In [192]:
bb = aa.copy();
bb[0]=122
bb

array([122,   2,   3])

In [194]:
bb+2

array([124,   4,   5])

In [196]:
bb-44

array([ 78, -42, -41])

In [198]:
np.cos(bb)

array([-0.86676709, -0.41614684, -0.9899925 ])

In [204]:
#Linear

In [220]:
x = np.ones((2,4))
print(x)
y = np.full((4,3),2)
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [222]:
np.matmul(x,y)

array([[8., 8., 8.],
       [8., 8., 8.]])

### Stat

In [230]:
s = np.array([[1,2,3,4],[3,4,5,6]])
np.sum(s,axis=0)

array([ 4,  6,  8, 10])

In [232]:
v = np.array([1,2,3,4])
w = np.array([3,4,5,6])

np.vstack([w,v,w])

array([[3, 4, 5, 6],
       [1, 2, 3, 4],
       [3, 4, 5, 6]])

In [234]:
np.hstack((w,w,v))

array([3, 4, 5, 6, 3, 4, 5, 6, 1, 2, 3, 4])

In [242]:
data = np.genfromtxt('num.text',delimiter=',')
print(data)

[[ 1.  3.  4.  5.  6.]
 [ 3.  4.  5.  6.  7.]
 [ 2.  3.  4.  5.  7.]
 [ 9.  0.  5.  5.  6.]
 [ 1.  2. 33. 34.  4.]]


In [244]:
data.astype('int32')

array([[ 1,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  7],
       [ 9,  0,  5,  5,  6],
       [ 1,  2, 33, 34,  4]], dtype=int32)

In [252]:
data>=3

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [False, False,  True,  True,  True]])

In [250]:
data[data>=3]

array([ 3.,  4.,  5.,  6.,  3.,  4.,  5.,  6.,  7.,  3.,  4.,  5.,  7.,
        9.,  5.,  5.,  6., 33., 34.,  4.])

In [256]:
q = np.array([1,2,2,2,3,4,5,6])
q[[1,2,3]]


array([2, 2, 2])

In [270]:
np.all(data>30, axis=1)

array([False, False, False, False, False])

In [272]:
data[2:4,1:3]

array([[3., 4.],
       [0., 5.]])

In [274]:
data[[0,1,2,3],[1,2,3,4]]

array([3., 5., 5., 6.])

In [5]:
a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
res = a1 + a2
print(res)

[[ 3  7 11]
 [ 9 13 17]]


In [7]:
food_data = np.array([[0.8, 2.9, 3.9], 
                      [52.4, 23.6, 36.5],
                      [55.2, 31.7, 23.9],
                      [14.4, 11, 4.9]])
# Caloric values per gram
caloric_values = np.array([3, 3, 8]) 
# Broadcast caloric values to match food data
caloric_matrix = caloric_values 

# Calculate calorie breakdown for each food
calorie_breakdown = food_data * caloric_matrix
print(calorie_breakdown)

[[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]


In [ ]:
def get_matrix():
    """Function to take user input for a matrix."""
    rows = int(input("Enter number of rows: "))
    cols = int(input("Enter number of columns: "))
    print("Enter matrix row by row, separating numbers with spaces:")
    matrix = []
    for _ in range(rows):
        matrix.append(list(map(float, input().split())))
    return np.array(matrix)

def matrix_operations():
    """Function to perform matrix operations."""
    print("\nMatrix Calculator - Choose an Operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Scalar Multiplication")
    print("5. Transpose")
    print("6. Determinant")
    print("7. Inverse")
    print("8. Eigenvalues & Eigenvectors")
    print("9. Exit")
    
    choice = input("Enter choice (1-9): ")
    
    if choice in ('1', '2', '3'):
        print("\nEnter first matrix:")
        A = get_matrix()
        print("\nEnter second matrix:")
        B = get_matrix()
        if choice == '1':
            print("\nResult of Addition:")
            print(A + B)
        elif choice == '2':
            print("\nResult of Subtraction:")
            print(A - B)
        elif choice == '3':
            print("\nResult of Multiplication:")
            print(np.dot(A, B))
    
    elif choice == '4':
        print("\nEnter matrix:")
        A = get_matrix()
        scalar = float(input("Enter scalar value: "))
        print("\nResult of Scalar Multiplication:")
        print(A * scalar)
    
    elif choice == '5':
        print("\nEnter matrix:")
        A = get_matrix()
        print("\nTranspose of the Matrix:")
        print(A.T)
    
    elif choice == '6':
        print("\nEnter square matrix:")
        A = get_matrix()
        if A.shape[0] != A.shape[1]:
            print("Error: Determinant can only be computed for square matrices.")
        else:
            print("\nDeterminant:", np.linalg.det(A))
    
    elif choice == '7':
        print("\nEnter square matrix:")
        A = get_matrix()
        if A.shape[0] != A.shape[1]:
            print("Error: Inverse can only be computed for square matrices.")
        else:
            try:
                print("\nInverse:")
                print(np.linalg.inv(A))
            except np.linalg.LinAlgError:
                print("Error: Matrix is singular and cannot be inverted.")
    
    elif choice == '8':
        print("\nEnter square matrix:")
        A = get_matrix()
        if A.shape[0] != A.shape[1]:
            print("Error: Eigenvalues can only be computed for square matrices.")
        else:
            eigenvalues, eigenvectors = np.linalg.eig(A)
            print("\nEigenvalues:", eigenvalues)
            print("\nEigenvectors:")
            print(eigenvectors)
    
    elif choice == '9':
        print("Exiting program.")
        return
    
    else:
        print("Invalid choice. Please select a valid option.")
    
    # Run again
    matrix_operations()

if __name__ == "__main__":
    matrix_operations()



Matrix Calculator - Choose an Operation:
1. Addition
2. Subtraction
3. Multiplication
4. Scalar Multiplication
5. Transpose
6. Determinant
7. Inverse
8. Eigenvalues & Eigenvectors
9. Exit


Enter choice (1-9):  8



Enter square matrix:


Enter number of rows:  2
Enter number of columns:  2


Enter matrix row by row, separating numbers with spaces:


 2 3
 3 4



Eigenvalues: [-0.16227766  6.16227766]

Eigenvectors:
[[-0.81124219 -0.58471028]
 [ 0.58471028 -0.81124219]]

Matrix Calculator - Choose an Operation:
1. Addition
2. Subtraction
3. Multiplication
4. Scalar Multiplication
5. Transpose
6. Determinant
7. Inverse
8. Eigenvalues & Eigenvectors
9. Exit


In [14]:
vector_a = 2 + 3j
vector_b = 4 + 5j
 
product = np.dot(vector_a, vector_b)
print("Dot Product  : ", product)

Dot Product  :  (-7+22j)
